## Series

In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
a=pd.Series([1,2,3,4,5])

In [4]:
type(a.dtype)

numpy.dtype[int64]

In [5]:
b={"day1": 420, "day2": 380, "day3": 390}

c=pd.Series(b)
print(c)

day1    420
day2    380
day3    390
dtype: int64


In [6]:
marks=[34,56,43,65,76,87,34,34,54,65]
name=['sohan','ram','mohan','prashant','rohit','abhishek','gabbar','himanshu','ankit','raushan']

classMarks=pd.Series(data=marks,index=name)
print(classMarks)

sohan       34
ram         56
mohan       43
prashant    65
rohit       76
abhishek    87
gabbar      34
himanshu    34
ankit       54
raushan     65
dtype: int64


In [12]:
data=pd.read_csv('./data/random.csv',header=None).squeeze('columns')
print(data)

    0     1     2     3    4      5      6      7      8     9   ...    20  \
0  279  8187  8866  7618  770  55700  32155  21777  38136  1435  ...  3114   

     21   22    23    24    25     26   27    28    29  
0  2895  223  9323  5482  1140  14850  477  2396  2438  

[1 rows x 30 columns]


In [14]:
survey=pd.read_csv('./data/annual-survey.csv',usecols=['value']).squeeze('columns')
print(survey)

0      46134
1          0
2        279
3       8187
4       8866
       ...  
105        0
106      169
107       36
108       36
109      489
Name: value, Length: 110, dtype: object


In [15]:
data.head()

0     1     2     3    4      5      6      7      8     9   ...    20  \
0  279  8187  8866  7618  770  55700  32155  21777  38136  1435  ...  3114   

     21   22    23    24    25     26   27    28    29  
0  2895  223  9323  5482  1140  14850  477  2396  2438  

[1 rows x 30 columns]

In [16]:
survey.head()

0    46134
1        0
2      279
3     8187
4     8866
Name: value, dtype: object

In [17]:
survey_data=pd.read_csv('./data/annual-survey.csv')

In [18]:
survey_data.head()

year industry_code_ANZSIC               industry_name_ANZSIC rme_size_grp  \
0  2011                    A  Agriculture, Forestry and Fishing          a_0   
1  2011                    A  Agriculture, Forestry and Fishing          a_0   
2  2011                    A  Agriculture, Forestry and Fishing          a_0   
3  2011                    A  Agriculture, Forestry and Fishing          a_0   
4  2011                    A  Agriculture, Forestry and Fishing          a_0   

                                          variable  value               unit  
0                                    Activity unit  46134              COUNT  
1                           Rolling mean employees      0              COUNT  
2                          Salaries and wages paid    279  DOLLARS(millions)  
3  Sales, government funding, grants and subsidies   8187  DOLLARS(millions)  
4                                     Total income   8866  DOLLARS(millions)

In [19]:
survey_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   year                  110 non-null    int64 
 1   industry_code_ANZSIC  110 non-null    object
 2   industry_name_ANZSIC  110 non-null    object
 3   rme_size_grp          110 non-null    object
 4   variable              110 non-null    object
 5   value                 110 non-null    object
 6   unit                  110 non-null    object
dtypes: int64(1), object(6)
memory usage: 6.1+ KB


In [20]:
survey_data.describe()

year
count   110.0
mean   2011.0
std       0.0
min    2011.0
25%    2011.0
50%    2011.0
75%    2011.0
max    2011.0

## DataFrames

In [21]:
import numpy as np

In [22]:
a= np.random.randn(5,5)
print(a)

[[-0.18603949  0.5068767  -1.12863297  0.04853     2.0562977 ]
 [ 0.39204546  0.49467609 -1.84801854 -0.91527816 -0.58946273]
 [-0.8719044   1.60702356  1.29345533  1.88499584  0.80246094]
 [ 0.09447467  1.3344551   0.67468575 -0.18932891  1.3892407 ]
 [ 0.80171728 -0.71811922  0.41170842  0.77257823  0.94912518]]


In [23]:
df=pd.DataFrame(a,columns=['a','b','c','d','e'])
print(df)

          a         b         c         d         e
0 -0.186039  0.506877 -1.128633  0.048530  2.056298
1  0.392045  0.494676 -1.848019 -0.915278 -0.589463
2 -0.871904  1.607024  1.293455  1.884996  0.802461
3  0.094475  1.334455  0.674686 -0.189329  1.389241
4  0.801717 -0.718119  0.411708  0.772578  0.949125


In [24]:
df1=pd.read_csv('./data/startups.csv')
# print(df1)
df1

Startup Name           City       Industry  Funding Raised (in millions)  \
0     Acme Corp  San Francisco     Technology                          10.5   
1      Blue Sky       New York     E-commerce                           5.2   
2    Green Leaf         London         Health                           3.7   
3    Red Rocket         Berlin       Software                           8.9   
4  Yellow Brick          Tokyo  Entertainment                           2.1   

   Number of Employees  
0                   50  
1                   20  
2                   10  
3                   30  
4                   15

In [25]:
df1.size

25

In [26]:
df1.shape

(5, 5)

In [28]:
data=pd.read_csv('./data/startups.csv')
print(data)

   Startup Name           City       Industry  Funding Raised (in millions)  \
0     Acme Corp  San Francisco     Technology                          10.5   
1      Blue Sky       New York     E-commerce                           5.2   
2    Green Leaf         London         Health                           3.7   
3    Red Rocket         Berlin       Software                           8.9   
4  Yellow Brick          Tokyo  Entertainment                           2.1   

   Number of Employees  
0                   50  
1                   20  
2                   10  
3                   30  
4                   15  
